#!c:\perl\bin\perl.exe
use CGI qw(:standard);
use CGI::Carp qw(fatalsToBrowser);


my $cgi = new CGI;
my $text_file = $cgi->param('text_seq');
my $file = $cgi->param('file');


my $name = (); 
 
 my @file_data=();
 
 if($file=~m/(\.txt|\.fasta)$/ig )
 {
  	$name = $file; 
 	open(LOCAL, ">","$name") or carp $!; 
 	while(<$file>) { print LOCAL $_; } 
 }
 else
 {
 	open(LOCAL, ">","text_area_file.txt") or carp $!; 
 	print LOCAL $text_file;
 	$name="text_area_file.txt";
 }
 
 
 close(LOCAL);
 
 
   use strict;
   
   use TPMorder;
   use Storable;
   use Benchmark;
   
   my $st = Benchmark->new();
   
   
  
   
   # MAKE OBJECT OF THE TPMorder CLASS
   
   my $tpm_2 = TPMorder->new();
   # PROCESS MULTIPLE FASTA FILE IN TO HASH
   
   my $seq_hash1 = $tpm_2->file_process($name);
   
   # CALCULATE TPM FOR GIVEN ORDER
   
   my $self_mod1 = $tpm_2->TPM_main(6);
   
   
   
   my $hashref = retrieve('file');
   my $result = $tpm_2->distance_matrix($hashref);


my $name = (); 
my @file_data=();
my @split_result=();
my $count = 0;
 my @time = `time`;
 $time[0]=~s/(.*is\:|\:|\.|\s|\/)/\_/g;
 my @date = `date`;
 $date[0]=~s/(.*is\:|\:|\.|\s|\-|\/)/\_/g;

my $name = "result$date[0]$time[0].txt";

open(OUT,">RESULT_TEXT/$name");

print OUT "\# This output is generated by HIVsubtyping server
\# Method: Markov Chain Based Subtyping
\# © Bioinformatics Centre, University of Pune, India\n\n";

print OUT "PREDICTED SUBTYPE\tQUERY SEQUENCE\n";
#print OUT "@{$result}","\n";
foreach my $res (@{$result})
{
@split_result = split("\t",$res); 
$count++;
next if ($count == 1 );
$split_result[0]=~s/\n//g;

print OUT "\t$split_result[1]\t\t";
print OUT "$split_result[0]\n";
@split_result=();
}
close(OUT);


print "Content-type: text/html\n\n";

print "
<html>

<head>

<title>Subtyping_Result</title>

<LINK href=\"../CSS/ser.css\" rel=\"stylesheet\" type=\"text/css\">

<script type=\"text/javascript\">
function eraseText() {
document.getElementById(\"reset\").value = \"\";
}
</script>

</head>

<body bgcolor = \"\#5F5353\">


<div align=\"center\">
  <table border =\"0\" width=\"75%\" height=\"1\" cellpadding=\"0\" frame=\"box\">
    <tr bgcolor = \"#EBEBCC\">
      <td width=\"75%\" height=\"1\" colspan=\"6\">
        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <a href = \"../index.html\">  Home</a>&nbsp;&nbsp;&nbsp;&nbsp; <a href = \"../CONTACTS/contacts.html\"> Contact us</a></p>
      </td>
    </tr>
  <center>
    <tr>
      <td width=\"75%\" height=\"200\" colspan=\"6\"><img border=\"0\" src=\"../IMAGES/sh.jpeg\" width=\"100%\" height=\"100%\"></td>
    </tr>
    <tr bgcolor = \"#CECBCB\" align = \"center\">
      <td width=\"328\" height=\"16\"></td>
      <td width=\"189\" height=\"16\"><a style=\"font-family: Times New Roman; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: 2; text-align: -webkit-right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; font-size: medium\" href=\"../tools.htm\">
     Tools</a><span style=\"color: rgb(0, 0, 0); font-family: 'Times New Roman'; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: 2; text-align: -webkit-right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; font-size: medium; display: inline !important; float: none; \">&nbsp;</span></td>
      <td width=\"90\" height=\"16\"><span style=\"color: rgb(0, 0, 0); font-family: 'Times New Roman'; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: 2; text-align: -webkit-right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; font-size: medium; display: inline !important; float: none; \"></span><a href=\"../DATASETS/dataset.html\" style=\"font-family: 'Times New Roman'; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: 2; text-align: -webkit-right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; font-size: medium; \">Datasets</a><span style=\"color: rgb(0, 0, 0); font-family: 'Times New Roman'; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: 2; text-align: -webkit-right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; font-size: medium; display: inline !important; float: none; \">&nbsp;<span class=\"Apple-converted-space\">&nbsp;</span></span></td>
      <td width=\"99\" height=\"16\"><a href=\"../VALIDATION/validation.html\" style=\"font-family: 'Times New Roman'; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: 2; text-align: -webkit-right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; font-size: medium; \">Validation</a><span style=\"color: rgb(0, 0, 0); font-family: 'Times New Roman'; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: 2; text-align: -webkit-right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; font-size: medium; display: inline !important; float: none; \">&nbsp;</span></td>
      <td width=\"125\" height=\"16\"><span style=\"color: rgb(0, 0, 0); font-family: 'Times New Roman'; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: 2; text-align: -webkit-right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; font-size: medium; display: inline !important; float: none; \"><span class=\"Apple-converted-space\">&nbsp;&nbsp;</span></span><a href=\"../REFERENCES/references.html\" style=\"font-family: 'Times New Roman'; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: 2; text-align: -webkit-right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; font-size: medium; \">References</a><span style=\"color: rgb(0, 0, 0); font-family: 'Times New Roman'; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: 2; text-align: -webkit-right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; font-size: medium; display: inline !important; float: none; \">&nbsp;<span class=\"Apple-converted-space\">&nbsp;</span></span></td>
      <td width=\"95\" height=\"16\"><a href=\"../EXAMPLES/examples.html\" style=\"font-family: 'Times New Roman'; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: 2; text-align: -webkit-right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; font-size: medium; \">Example</a><span style=\"color: rgb(0, 0, 0); font-family: 'Times New Roman'; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: 2; text-align: -webkit-right; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; font-size: medium; display: inline !important; float: none; \">&nbsp;</span></td>
    </tr>
    <tr bgcolor =\"#EBEBEB\" cellpadding = \"100\">
      <td width=\"75%\" height=\"495\" colspan=\"6\" vlign =\"center\" >
      ";
 
 
   
print "
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<blockquote>
<font size=\"5\" face = \"cambria\"><b>SUBTYPING RESULTS :</b></font><blockquote></p><br><br>
";

print "<table  align = center  cellpadding = 5 frame=box>";     
my @split_result=();
my $count = 1;
my $flag = 0;






foreach my $res (@{$result})
{
#print $res,"\n";
@split_result= split("\t",$res); 

	if($count == 1)
	{
		print "<tr align =center bgcolor = pink><th>$split_result[0]</th><th>$split_result[1]</th></tr>";
		
		$count=0;
	}
	elsif($flag==0)
	{
		print "<tr align =center bgcolor =#ECC87A><td>$split_result[0]</td><td>$split_result[1]</td></tr>";
		
		#print OUT "";		
		$flag=1;
	}
	elsif($flag==1)
	{
		print "<tr align =center bgcolor =#EBEBEC><td>$split_result[0]</td><td>$split_result[1]</td></tr>";
		
		#print OUT "";
		$flag=0;
	}
@split_result=();
}

print "</table>";           
  
 print "<br><br><br>Result can be downloaded here<br><a href= \"RESULT_TEXT/$name\">$name</a>";
    
     my $end = Benchmark->new();
     
   my $lag = timediff($st,$end);
 print "<br><br> &nbsp;&nbsp;&nbsp;&nbsp;";
 #print "Time Required for results is", timestr($lag);
          
print "  
</td>
    </tr>
    <tr bgcolor = \"#FF9900\">
      <td width=\"75%\" height=\"19\" colspan=\"6\" align = \"center\">© Bioinformatics Centre, University of Pune, India</td>
    </tr>
    
  </table>
</div>

</body>

</html>
";

      
      
      
      
      
      
      
      
    